name: docs
on:
  push:
    branches:
      - develop
permissions:
  contents: write
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name a.faria
          git config user.email 43576576+movedempackets@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Python Poetry
        run: pip install poetry==1.8
      - name: Install development dependencies
        run: poetry install --only dev
      - name: Publish documentation
        run: poetry run mkdocs gh-deploy --force
